ocs2_gazebo:
  joint_controller:
      type: switched_model/JointController
      joints: ["LF_HAA", "LF_HFE", "LF_KFE","RF_HAA", "RF_HFE", "RF_KFE","LH_HAA", "LH_HFE", "LH_KFE","RH_HAA", "RH_HFE", "RH_KFE"]