input_sources:
  front_camera: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
    topic: /camera/depth/points_downsampled
    queue_size: 1
    publish_on_update: false # Whether to publish the elevation map after a callback from this source.
    sensor_processor:
      type: perfect

  rear_camera: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
    topic: /rear_camera/depth/points_downsampled
    queue_size: 1
    publish_on_update: false # Whether to publish the elevation map after a callback from this source.
    sensor_processor:
      type: perfect

  left_camera: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
    topic: /left_camera/depth/points_downsampled
    queue_size: 1
    publish_on_update: false # Whether to publish the elevation map after a callback from this source.
    sensor_processor:
      type: perfect

  right_camera: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
    topic: /right_camera/depth/points_downsampled
    queue_size: 1
    publish_on_update: true # Whether to publish the elevation map after a callback from this source.
    sensor_processor:
      type: perfect
map_frame_id: "world"
robot_base_frame_id: "base"
robot_pose_with_covariance_topic: "" # Leaving this empty skipps pose covariance updates.
robot_pose_cache_size: 40
track_point_frame_id: "base"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0

# Map.
length_in_x:                                3.0
length_in_y:                                3.0
position_x:                                 0.0
position_y:                                 0.0
resolution:                                 0.06
min_variance:                               0.0001
max_variance:                               0.05
mahalanobis_distance_threshold:             2.5
multi_height_noise:                         0.001
surface_normal_positive_axis:               z
fused_map_publishing_rate:                  0.5
enable_visibility_cleanup:                  true
visibility_cleanup_rate:                    1.0
scanning_duration:                          1.0

# Init submap
initialize_elevation_map:                   true
initialization_method:                      0
length_in_x_init_submap:                    3.0
length_in_y_init_submap:                    3.0
init_submap_height_offset:                  -0.01
init_submap_variance:                       0.001
target_frame_init_submap:                   world